### ISSUE TITLE
not running on os x 10.9.5

### ISSUE THREAD

**Issue by joernroeder** [tedsmith/quickhash#1]
I've downloaded the latest release and checked my mac store preferences, but the program crashes immediatly after double clicking it's icon. Do i need a newer os x version to get it running?

![screen shot 2015-10-22 at 20 35 08](https://cloud.githubusercontent.com/assets/270540/10674698/a99dd52c-78fc-11e5-96db-56a56b5a4066.PNG)

**Comment by tedsmith** [comment]
Hi

Sorry for the delay. I only just noticed the notification. 
sIt's built for Yosemite or El Capitan. I believe os x 10.9.5 is Mavericks? In which case, it may not work, as you identify. But Apple Mac systems are not my forte - so I am assuming. If possible, try it on a friend or colleagues Yosemite system and see if that works. If it does, than that answers the question. Could you let me know the outcome? Thanks

**Comment by tedsmith** [comment]
As no reply received, issue closed.
