### ISSUE TITLE
Feature request: Default preferences

### ISSUE THREAD

**Issue by Sheridan-Tech** [tedsmith/quickhash#102]
I would really love for there to be preferences for the default tab and algorithm or at the very least to be able to remember the last state so it will default to that upon re-entry of the app. 99% of the time I am selecting the File tab and using SHA256.

**Comment by cspacone** [comment]
+1 I note there is an XML file in the directory from which I run the program. Does this indicate that there is a line that can be entered to set various default values?

-Chris

**Comment by tedsmith** [comment]
Has been added in v3.3.3 branch for Windows and Linux. Hoping to release a compiled version in the next day or so

**Comment by tedsmith** [comment]
This is, in part, satisfied in v3.3.3 and (coming soon) v3.3.4
