### ISSUE TITLE
Copy - Save Results (CSV)? Does not work.

### ISSUE THREAD

**Issue by a3ilson** [tedsmith/quickhash#104]
When utilizing the tool and specifically the "Copy" function which copies the files and hashes (dialog displays all hash values) but when saving the output (CSV), it'll save a file, but the contents are empty and only the headers are visible.

- [ ] fix the "Copy" function when the "save results (CSV)?" is ticked to actually save the results
- [ ] the "Save results (CSV)?" option is ticked, the delaminated should be mandatory or defaulted to comma
- [ ] fix the "Copy" function when the "save results (CSV)?" is ticked the file actually writes to disk (works when saving to desktop but not other paths)

Multiple Windows 10 and 11 hosts running 64-bit tested/confirmed.

**Comment by tedsmith** [comment]
I swear there was a bug report for this somewhere already but I cant seem to find it now. It is a known issue that I accidentally introduced with v3.3.0 or 3.3.1 I think. The good news is you can still save by right clicking the results grid and choose Save to CSV that way. So it's not a "one chance or else" scenario. Though it is on my To Do list. Thanks for raising it and reminding me.

**Comment by tedsmith** [comment]
Fixed in latest commit to base for v3.3.2. Will be released on website in next few hours.
