### ISSUE TITLE
Apple Silicon version?

### ISSUE THREAD

**Issue by taprobane99** [tedsmith/quickhash#107]
Quickhash is great!

Would it be possible to make an apple silicon (M1, M2) native version?

**Comment by tedsmith** [comment]
Ha...not easily right now. It should run on an M1\M2 Mac if granted permission though thanks to the Rosetta Abstraction layer. But it is definately not natively compiled for that architecture.

**Comment by tedsmith** [comment]
I may have a solution for the program to run in M1 Mac's now. Watch this space.

**Comment by tedsmith** [comment]
From what I hear, the latest version runs on M1 - it works on my M1 Mac, at least. Not sure about M2. [https://www.quickhash-gui.org/download/quickhash-gui-v3-3-4-apple-osx/](url)
