### ISSUE TITLE
SHA-3 ?

### ISSUE THREAD

**Issue by ghost** [tedsmith/quickhash#120]

**Comment by darealshinji** [comment]
https://en.wikipedia.org/wiki/SHA-3

Seems to be supported by the program.

![sha3](https://github.com/tedsmith/quickhash/assets/5700937/d1e29957-0f17-4a7b-b9ef-70b5570dd702)

**Comment by ghost** [comment]
@darealshinji 

Yeah but which one ?
SHA3-224
SHA3-256
SHA3-384
SHA3-512
SHAKE128
SHAKE256

**Comment by darealshinji** [comment]
SHA3-256 it seems: https://github.com/tedsmith/quickhash/blob/master/unit2.pas#L3945

**Comment by ghost** [comment]
@darealshinji Thank you :)
