### ISSUE TITLE
Unable to create file Quickhash-GUI.xml: Access denied (Windows)

### ISSUE THREAD

**Issue by Chlara** [tedsmith/quickhash#121]
Hi
I have the problem with following error:
 
![Screenshot 2024-04-30 111106](https://github.com/tedsmith/quickhash/assets/1552939/7a7c6c3d-6c16-455f-ba2c-3253691aa727)

When Quickhash-GUI has been installed on Windows with administration rights the normal user can not close Quickhash-GUI without getting this error and killing the program. 
I tried to find if I can configure the path, where Quickhash-GUI.xml should been written or if I want to save this information’s. But I couldn’t find those options.
It would be nice if this little problem would not give such a massive error or each user could define the options.
Chlara

**Comment by tedsmith** [comment]
Hi Chlara - sorry for the delay in replying. I didn't notice this for a while

The xml file is typically created for most users on most systems but sometimes permissions issues can cause a problem. The 'severity' of the error is, as you state, annoyingly alarming. It is, however, a pre-compiled message that is delivered when there is a risk of a memory stack problem. So the data it refers to is not the users, but the system stack. But of course users of the tool won't know that, but it is not something I can control - at least, not that I know of easily. There is always a way but that is one I never found a solution to.
