### ISSUE TITLE
@darealshinji - LPR and LPI files

### ISSUE THREAD

**Issue by tedsmith** [tedsmith/quickhash#18]
Hiya @darealshinji 

I was checking the code of v2.8.1 last night, and if I clone the repo and open the LPR file using Lazarus in Windows, the QuickHash interface includes all of my latest changes. Most notably, the little "donate now" line, in red, at the top. 

Yet if I clone the repository and open the LPR file on a Linux platform and then open it with Lazarus, it shows the v2.8.0 interface! 

I can't quite work out why, because a new LPI file is creates after the LPR project file has been opened in Lazarus. But I recall you committing the Linux.lpi file for a reason I can't now remember. 

If you clone the repo in Linux and open the LPR file, do you see the v2.8.0 interface of QuickHash or the v2.8.1 version?

**Comment by darealshinji** [comment]
unit2.lrs needs to be updated.

**Comment by darealshinji** [comment]
The resource file can be generated on command line with `lazres unit2.lrs unit2.lfm`.
Maybe I should add this to the build system?

**Comment by tedsmith** [comment]
You've a better grasp of some of the Lazarus files than I have for sure, and I've been using it for several years! Thanks for that. For info, in case I ask again in the future! : http://wiki.freepascal.org/Lazarus_Resources#Lazarus_Resource_Form_File 

So I just moved a button a pixel, then moved it back again, and then after recompiling the project, the interface has all the updates needed. So I've just committed unit2.lrs to master. 

> "Maybe I should add this to the build system?" : yes, good idea. It would be helpful I think.

**Comment by darealshinji** [comment]
The build system was updated.

**Comment by darealshinji** [comment]
Should this be closed as the issue is now fixed?

**Comment by tedsmith** [comment]
Agreed. Thanks
