### ISSUE TITLE
Linking Linux binaries with -z relro

### ISSUE THREAD

**Issue by darealshinji** [tedsmith/quickhash#2]
I don't know much about Pascal or Lazarus. Is it possible to link the Linux binaries with `-z relro`? When using gcc that would be done by adding `-Wl,-z,relro` to the LDFLAGS (see https://wiki.ubuntu.com/ToolChain/CompilerFlags#A-Wl.2C-z.2Crelro).

**Comment by tedsmith** [comment]
Hi @darealshinji ...I have to be honest...I have no idea! I'll ask in the development forums. Can I ask what the reasons are for this? It seems like it is to protect installed binaries? Is that correct?

**Comment by darealshinji** [comment]
Yes. Linking with `-z relro` is nowadays done by default on most distros, that's why I'm asking. But it's not a big deal if you don't know how to do that.

**Comment by tedsmith** [comment]
Apparantly, Freepascal Compiler adds to the linker commandline via the -k parameter:

-k"-z zelro"  or -k-z  -kzelro

If I can work out how to do it, would QH have a better chance of been included in distributions?

**Comment by darealshinji** [comment]
To be officially included in distributions QH and its dependencies should be under a free license (dcpcrypt is MIT, right?). And it should be possible to build it from the original source files with command line options. But there are always exceptions. But paying attention to things like adding hardening flags to the compilers and linker is helpful too I guess.

**Comment by tedsmith** [comment]
Hi

Yes, MIT for dcpcrypt, which I use for SHA256 and SHA512 implementation. The native MD5 and SHA-1 implementation of FreePascal is quicker than DCPCrypts implementation so I use that for those two. 

If the git repo is used, it should be compilable using Lazarus, and although I'm not familiar with compiling via the terminal, I know it is possible, and apparantly doing so with -k-z -kzelro will work that way and that way only I believe. I will have to try it out when I get chance. 

If it does work, may I ask you about how to submit to a distro repo? Seems you're involved with Debian? Is that right?

**Comment by darealshinji** [comment]
I'm just an Ubuntu user who is interested in packaging and generally in free software.
You can request your package to be added to Debian via email: https://www.debian.org/devel/wnpp/#l2
Once it's in Debian, it'll automatically become available in Ubuntu too.

By the way I have a question about the license: according to the pdf user manual the license is GPLv3, while the included LICENSE.txt file provides the text of the GPLv2. I'm also a little unsure about the additional clause from the manual:
>If you fork this program or commercialise it you
>must notify Ted Smith and include his name in the documentation that accompanies
>the product (typically 'Acknowledgments' file or 'Authors' file).

While the second part of that statement should be covered by the license anyway, I'm not so sure about whether the `must notify` thing might somehow contradict the license. Well, I'm no lawyer, but I know that at least the Debian guys are very nit-picking when it comes to stuff like that (they even consider the GNU Free Documentation License a non-free license).

**Comment by tedsmith** [comment]
Thanks for that. You're right - the entry in the PDF was a while ago, but I recently got to grasps a bit more with the difference between v2 and v3 and forgot to update them in line with each other. I'll fix that for the next release. 

The second point related to something I read recently that stated that there have been incidents of people forking an OS project who worked for a commercial company, and then the commercial company turned round to claim IP rights over the original. So I added it to try and safeguard against that but perhaps that was a poor effort at doing so, now that you point it out.

**Comment by tedsmith** [comment]
@darealshinji - does this help at all : https://github.com/tedsmith/quickhash/releases/tag/DebianPackage-1.0

**Comment by darealshinji** [comment]
> does this help at all

Yes, but I will modify it and use the new Makefile. But first I want to implement `make install` and make sure a desktop menu entry will be installed too. Do you have the original file for the Windows icon? If not, I will create PNG icons for Linux from the ICO file.

**Comment by tedsmith** [comment]
Excellent. Exciting stuff! Thankyou. 

I was looking for the original logo file myself. I found it years ago but I'm not sure I ever saved a "proper" version. Anyway, the attached PNG is about 200Kb which will work I hope. 
![quickhash-logo](https://cloud.githubusercontent.com/assets/1560598/21397025/21c20d60-c79a-11e6-943c-a93a2d55e744.png)

**Comment by darealshinji** [comment]
I removed the background and cropped the image, which I think looks better (although it's a bit "edgy" now; I'm not good at image manipulation):
![quickhash_128](https://cloud.githubusercontent.com/assets/5700937/21399654/be0e1c4c-c7ac-11e6-98e8-6bd4922f41db.png)

This is what it looks like in my task bar:
![shot](https://cloud.githubusercontent.com/assets/5700937/21399672/cae99900-c7ac-11e6-8aaa-c084c4b747f6.png)

Here I kept the background, but cropped the image:
![cropped](https://cloud.githubusercontent.com/assets/5700937/21399850/b1334d2a-c7ad-11e6-8be2-8fee533e4738.png)

What do you think?

**Comment by tedsmith** [comment]
Looks great @darealshinji !! Well done, and thank you!

**Comment by darealshinji** [comment]
I'm closing this, since the original linking issue was resolved.

**Comment by tedsmith** [comment]
Given you a mention : http://quickhash-gui.org/debian-package-coming-soon/
