### ISSUE TITLE
typo error in your readme

### ISSUE THREAD

**Issue by Xor-el** [tedsmith/quickhash#26]
You have /CloneOfQuickHashProject/HashLib4Pascal/HashLib/src/Packages/FPCdcpcrypt_laz.lpk as the path to the HashLib4Pascal package instead of /CloneOfQuickHashProject/HashLib4Pascal/HashLib/src/Packages/FPC/HashLib4PascalPackage.lpk in your readme.

**Comment by darealshinji** [comment]
Thanks, fixed.

**Comment by Xor-el** [comment]
An error still exists,  there is no FPCdcpcrypt_laz.lpk in the directory path,  what we have there is HashLib4PascalPackage.lpk

**Comment by darealshinji** [comment]
Okay, fixed it.
