### ISSUE TITLE
Inconsistent layout on Algorithm box

### ISSUE THREAD

**Issue by darealshinji** [tedsmith/quickhash#27]
On the first tab there's enough space for the `xxHash64` text but almost no gap between the `Alogrithm`and the `Text Hashing` box.
The other tabs have a bigger gap but not enough space for the `xxHash64` text.

![s1](https://user-images.githubusercontent.com/5700937/27662098-cf6a6280-5c5c-11e7-94c4-adcedfda95ea.png)
![s2](https://user-images.githubusercontent.com/5700937/27662101-d2f364ce-5c5c-11e7-952b-b4bab7e4ada6.png)

**Comment by tedsmith** [comment]
I noticed that but it seems to vary from one OS to another! But I guess the safest step would be to make the Algorithm box slightly wider on the other tabs, to make it the same as the Text tab.

**Comment by tedsmith** [comment]
Hopefully OK now.  

![screenshot-quickhash v2 8 3 - the easy and convenient way to hash data in linux osx and windows](https://user-images.githubusercontent.com/1560598/27687498-fa6758cc-5cce-11e7-9a85-ae9e7133595d.png)
![screenshot-quickhash v2 8 3 - the easy and convenient way to hash data in linux osx and windows-1](https://user-images.githubusercontent.com/1560598/27687499-fa69bc52-5cce-11e7-9fa5-f9330d687226.png)

**Comment by darealshinji** [comment]
Now there's enough space. But now I realize how the outlines of the boxes are invisible on your Linux Mint gtk theme. I think that looks actually kinda good. Is it maybe possible to force this so that the lines will not be visible on any theme or OS?

**Comment by tedsmith** [comment]
No idea...it's certainly not project specific, because the same project looks different on your Linux system compared to mine and my Windows system compared to the Linux ones. So it must be something to do with how the Lazarus IDE behaves on the various platforms. Fairly sure I've never set an option or anything though to do that. Just does it automatically.
