### ISSUE TITLE
Using .fodt instead of .odt

### ISSUE THREAD

**Issue by darealshinji** [tedsmith/quickhash#29]
I was thinking, maybe the documents should be saved as .fodt (Flat XML ODT ) so that Github would actually generate a real diff. The diffs would still be quite huge, but it should be easier to see which parts of the document were changed.

**Comment by tedsmith** [comment]
Fair point. Never heard of FODT to be honest. Feel free to investigate further if you're interested. I'm not worried what version to use (ODT or FODT) as long as I can open and edit with LibreOffice.

**Comment by darealshinji** [comment]
Here would be such a diff: https://github.com/darealshinji/quickhash/commit/c120fe46662e8220558aa3f902baf9c29d9d2cf5

**Comment by darealshinji** [comment]
README1.odt doesn't seem to use any special formatting. Won't it be better to skip the office document and write it directly as a text file, preferably markdown format? Personally I would also save the changelog in a separate file.

**Comment by tedsmith** [comment]
Agreed. Thanks DRS :-) 

https://github.com/tedsmith/quickhash/pull/31 merged
