### ISSUE TITLE
SHA256 & SHA512 Crash

### ISSUE THREAD

**Issue by joshuaavalon** [tedsmith/quickhash#3]
I am using 2.6.6 on window 7. The program crashed when I tried to hash  a 200 MB file. It seems that you had addressed the problem in the front page in 2013

**Comment by tedsmith** [comment]
Screenshots? Error messages? 

Thanks
Ted

Date: Wed, 2 Mar 2016 05:18:11 -0800

**Comment by joshuaavalon** [comment]
It said it cannot open file. Ignore or terminate the problem

**Comment by tedsmith** [comment]
What was the file? i.e. what type of file was it? Is it possible it was open by another process? Can you try it again? 

QH does crash from time to time or generate the odd error message but it's downloaded over 1K a week by every country in the world except Antarctica and the North Pole. For the vast majority of people it just works, so when I get a message like this I need more information to troubleshoot it. Running process lists, screenshots, file types, storage medium etc etc.

**Comment by joshuaavalon** [comment]
It was a 7z file. I retried it (download it again) yesterday and it worked again. I am sure that I closed all other programs related to the file and restarted the program several times that day.

**Comment by tedsmith** [comment]
OK, cool. Glad it is working OK now. Ticket closed.
