### ISSUE TITLE
Please dont commit to master for now

### ISSUE THREAD

**Issue by tedsmith** [tedsmith/quickhash#32]
@darealshinji : I'm working on a big change to QH, by replacing the stringgrids for SQLite and DBGrid components. It's a big re-write of many parts of the program, and will probably result in a new v3.0 release when its done (which may be many weeks as I only work on it in the evenings when I get chance). 

Given the complexity, and given my limited grasp of git, and to avoid any wasting of your work or mine, can I ask that the master is not committed to. The current master is for v2.8.4

Thanks

**Comment by darealshinji** [comment]
Acknowledged.

**Comment by tedsmith** [comment]
I'll probably create a branch soon, so at least progressive changes get pushed to Git. And it will help to stagger the incorporation.

**Comment by darealshinji** [comment]
I think this can be closed, right?
