### ISSUE TITLE
Cannot compile on Lazarus 1.8.0 (Ubuntu 16.04)

### ISSUE THREAD

**Issue by darealshinji** [tedsmith/quickhash#38]
I've installed fpc 3.0.4 and compiled Lazarus 1.8.0. I've installed all required packages as mentioned in the README. But then compiling stops with the following errors:
```
unit2.pas(2190,51) Error: identifier idents no member "GetSelectedNodePath"
unit2.pas(2196,51) Error: identifier idents no member "GetSelectedNodePath"
unit2.pas(2546,38) Error: identifier idents no member "GetSelectedNodePath"
unit2.pas(2549,38) Error: identifier idents no member "GetSelectedNodePath"
```

**Comment by tedsmith** [comment]
I need to state in the readme that it must use fpc 3.0.2. And Lazarus 1.6.4. Sorry I forgot that. 
Ted


Sent from Yahoo Mail for iPhone


On Sunday, January 21, 2018, 1:18 am, darealshinji <notifications@github.com> wrote:


I've installed fpc 3.0.4 and compiled Lazarus 1.8.0. I've installed all required packages as mentioned in the README. But then compiling stops with the following errors:
unit2.pas(2190,51) Error: identifier idents no member "GetSelectedNodePath"
unit2.pas(2196,51) Error: identifier idents no member "GetSelectedNodePath"
unit2.pas(2546,38) Error: identifier idents no member "GetSelectedNodePath"
unit2.pas(2549,38) Error: identifier idents no member "GetSelectedNodePath"

**Comment by tedsmith** [comment]
Ps...I discovered this myself a few weeks ago when setting up some new virtual machines. Lots of the code needs adjusting for fpc 3.0.4

**Comment by darealshinji** [comment]
Thanks. After installing the right .deb packages from [SourceForge](https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%201.6.4/) it worked. I will do some tests and then update the Makefile.

**Comment by tedsmith** [comment]
Awesome. I have updated readme
