### ISSUE TITLE
FileS Tab - Grid to clipboard on OSX Fails

### ISSUE THREAD

**Issue by tedsmith** [tedsmith/quickhash#41]
Cant create the temp file on OSX in v3.0.0. Need to adjust where it is created

**Comment by darealshinji** [comment]
http://lazarus-ccr.sourceforge.net/docs/rtl/sysutils/gettempdir.html
Does this help for OSX and Windows?

**Comment by tedsmith** [comment]
Yes, for sure. Will use that. Thanks

**Comment by tedsmith** [comment]
Implemented in commit 90ca2437cc9079abcd94356cfedf08c47640156f and fixed.
