### ISSUE TITLE
No Tags/Releases for 3.0.1 & 3.0.2 on GitHub?

### ISSUE THREAD

**Issue by ravage84** [tedsmith/quickhash#48]
Hi Ted,

Nice software you built there. :heart: 

As a developer I'm used to find for each (downloadable) release of a software a corresponding git tag and often a GitHub release on the GithUb repo.

But it seems there is (at least) no git tag for 3.0.1 & 3.0.2, though there are downloads for these version.

[QH 3.0.2 (Windows)](https://quickhash-gui.org/download/quickhash-v3-0-2-windows/)
[QH 3.0.1 (Windows)](https://quickhash-gui.org/download/quickhash-v3-0-1-windows/)

[GitHub Tags of QH](https://github.com/tedsmith/quickhash/tags)
The latest release and tag is [3.0.0 on GitHub](https://github.com/tedsmith/quickhash/releases/tag/V3.0.0).

Is there a particular reason (like a defined process) for that circumstance or is it just an oversight?

**Comment by darealshinji** [comment]
@tedsmith You can create tags directly on Github. Go to "Releases -> Draf a new release" and then create a release tag from a specific commit.

![tag](https://user-images.githubusercontent.com/5700937/50044716-2bafbb00-0088-11e9-9229-9271c2af5da8.png)

**Comment by tedsmith** [comment]
I've just checked this while announcing the release of v3.3.0 and "master" was ticked by default which makes sense to me. I get the discussion here, in that it makes sense to mark it against a commit of an actual branch version. But, for now I'm going to stick with marking it against master. And I'll read up on this some more when I get some down time. Thanks for pointing it out though and for the direction here. Github is still something I am learning, as I go.
