### ISSUE TITLE
Do you have any GPG public key ? 

### ISSUE THREAD

**Issue by prog-amateur** [tedsmith/quickhash#65]
Hello, first of all, thank you so much for your very nice software. 
I have read [your blog announce about the code signed executables](https://quickhash-gui.org/v3-1-0-is-now-available/), and I understand it can be expensive. However, it means we (downloaders) are vulnerable to a risk of attack at any time. Please find below what I mean : 

**SHA check :** 
The SHA checksum is done by you when you upload the executable in your website. This is what you currently do. Then, it is verified by us after downloading the executable. This ensures that the file has not been modified in the meantime. 

**GPG check :** 
But who sent this unmodified file? You or a `Man in the middle` ? This is where the GPG public key allows to verify the origin of the file and ensure that you have uploaded the executable that we have downloaded.    

Softwares and distributions often provide both SHA-256 checksums and GPG digital signatures to verify their files. 

**QUESTIONS :** 
Therefore, please find my questions :

```
1. Why do not apply an SHA-256 algorithm (it's not much longer/heavier than the SHA-1)? 
2. Why do not propose a double check (SHA and GPG) for those wishing to ensure both authenticity and authenticity? 
```

It would be a bit of a shame for a software program that is supposed to check files to be the target of a Man in the middle attack. A GPG public key can be shared for example in this github (to ensure your website has not been compromised) and does not required a heavy workload to produce (and once it is uploaded, you don't need to maintain it). 

Please, what do you think ? 

_Note : Please don't take this criticism personally, I want it to be constructive and not hurt you. You did a very good job, and I can tell you that your software in one of my favorite integrity check softwares. Thank you very much for your feedback._

**Comment by tedsmith** [comment]
Hi

Sorry for the long delay. I didn't notice the post until just now. 

You are quite right. I probably should use SHA-256. Habbit I guess. 

Re GPG signatures. Funnily enough, that is what I am doing right now! I have enabled GPG code signing for code commits in Windows but am currently wrestling with Linux. You make a reasonable point. I will look into it. GPG keys are still a bit new to me (with regard to their use as you explain) so I will need to read up on it. 

Thanks

Ted

**Comment by tedsmith** [comment]
Other than the verified status of the code commits, do you happen to know how to locate and share a GPG public key, on Linux? Done a bit of Googling and it is not overly obvious to me. But I agree it would be a worthwhile endeavour.
