### ISSUE TITLE
Feature Request: Compute hashes of all files when drap&drop files

### ISSUE THREAD

**Issue by firstrose** [tedsmith/quickhash#66]
Drop arbitary file**s** will switch to "file" tab and only one file is hashed now.

**Comment by tedsmith** [comment]
It is not designed for that. Please use the "FileS" tab, select the folder containing the files in question, and it will hash them all that way.

**Comment by firstrose** [comment]
> 
> 
> It is not designed for that. Please use the "FileS" tab, select the folder containing the files in question, and it will hash them all that way.

FileS will also hash those doesn't need hash. That will waste time & I/O on large files.
Any better solution?
