### ISSUE TITLE
while processing, Quickhash-window looks like freezed

### ISSUE THREAD

**Issue by Golddouble** [tedsmith/quickhash#67]
System: MX Linux 19
PC: i5-generation 4

I would like to use this program to copy (and verify) huge amounts of files. My concern was, that maybe in rare cases there could be copy-errors, when I just use thunar for this.

So I found this program (I did not find any other program that can do this in Linux.).
I only need the "copy Tab".

So, for my first test I chose a file that is about 80 GB.
I pressed the "Go" button.

Now the behavior was not as expected. I expected, that now I can track the progress of taking hashes and copy files and can see the stage of the progress each time.

But after pressing the "go-Button" the whole window of quickhash looked like freezed. Nevertheless I was able to minimize and open again the window. After the window was open again, this window was simply grey. Nothing could be seen.

But as soon Quickhash was finished with hashing and copying, the window again showed its Gui. Copying was successful. It was only during the process, that the window was just grey and felt  like freezed.

Are you aware of this behavior?

**Comment by tedsmith** [comment]
Yes, and no. It is supposed to refresh intermittantly. But I have noticed on Linux it is not quite as good as in WIndows for that. Thanks for the note for sure.

**Comment by tedsmith** [comment]
I am working on v3.3.1 at the moment. The reason for what you describe is that the progress of the Copy tab is controlled by FILE COUNT not FILE SIZE. So, it has to hash the source file, then copy it, then hash it again, then move onto the next file. So, if you gacve it a large single file of 80Gb, the progress can the interface will be "locked" (un responsive) until it finishes that step with that file. After which the interface will refresh as it moves to the next file. If the next 1000 files are very small, the interface will appear responsive and the progress will move with every % of the overall file count. But, if you have 1000 files of 80Gb each, then QH will indeed appear rather "locked" and "unresponsive". If I ever manage to add multi-threading to it, I will be able to solve that. But until then, you will just have to be patient while it does its thing. Thanks

**Comment by Golddouble** [comment]
Thank you for your feedback. 
The most important thing is that the programme works properly. And it seems so.
