### ISSUE TITLE
Unable to Create File

### ISSUE THREAD

**Issue by js-limitless-factor** [tedsmith/quickhash#68]
MacOS ver: 10.15.3

Hi, am unable to create a file. It keeps prompt me an error message as attached screenshot. Please advice.

<img width="1017" alt="Screenshot 2020-03-23 at 9 30 41 AM" src="https://user-images.githubusercontent.com/49058086/77271263-37594b00-6ce9-11ea-8220-62983da41597.png">

Regards,
JS

**Comment by tedsmith** [comment]
That is odd. It is trying to create the output file (by the looks of it) to the root of your filesystem ('/'). Please try copying QuickHash to somewhere like your Documents folder in your home directory and retry.

**Comment by tedsmith** [comment]
PS...I notice that is version v3.1.0. Please try v3.2.0
