### ISSUE TITLE
Feature request: save-to-file option instead of displaying results in "fileS" tab

### ISSUE THREAD

**Issue by mike-lawrence** [tedsmith/quickhash#70]
I just computed the hashes for an entire 2TB drive only to discover that there's no save-to-file option, just the "clipboard" option which I clicked but caused the app to go non-responsive. Task manager shows it's probably accumulating the results into ram, but it strikes me that a better solution would be to give the user the ability to specify ahead of time that they wanted the results written to file before the hashing begins, and write to a specified file while the hashing progresses.

**Comment by mike-lawrence** [comment]
Indeed, it looks like the data is already saved in an sql file! (found by checking whether quickhash already had any files open). I can copy and use that for now, but it's hidden in a temp dir that is pretty cumbersome for the user to access. Better to have a true save option.

**Comment by tedsmith** [comment]
Right click, "Save to CSV" (and HTML is also an option, but has a much bigger storage requirement than CSV). 

But I agree that for large volumes of data, a streamed output might be a better option.

**Comment by tedsmith** [comment]
There's lots of new and improved features in v3.3.0 relevant to this, which is to be released in a week or so (the code is in the v3.3.0 branch here on Github). But one you will be interested in is the easy means to lookup the name and location of the SQLite file, via the Environment Checker, and the SQLite version in use, and a button to enable you to copy the DB for use with dedicated DB explorers. Along with a raft of right click menu options to clipboard, save as csv, html etc. So I will close this for now in the hope the new v3.3.0 addresses your needs. Visit the website next weekend, around the 29th, and the new version will hopefully be available. 
![Untitled1](https://user-images.githubusercontent.com/1560598/119278018-aea2ab80-bc1a-11eb-9a95-293cefb6a6f0.png)
