### ISSUE TITLE
[SUGGESTION] Make the compare folders more useful.

### ISSUE THREAD

**Issue by frenchiveruti** [tedsmith/quickhash#71]
Hi, I'll try to keep it simple, but it would be nice to have the folder comparison tab to 'print' out the files that actually differ or mismatch, so we can see what's the issue.  
For example today I compared two 300GB folders and I was clueless on where was the MISMATCH, because it didn't even print how many files were different.  
It ended up being a single desktop.ini file that was there, and that I found out after searching how to split the hash from the location using a CSV import into a spreadsheet and then doing an EQ(a,b) on all of them and looking for the FALSE values.
So.

- Have the files that don't match listed somewhere.
- Display how many files don't match.

Thank you.

**Comment by tedsmith** [comment]
Hopefully you'll find v3.2.0 better, released a few weeks ago, where things have been improved. https://www.quickhash-gui.org/downloads/
