### ISSUE TITLE
Debian Packager version 

### ISSUE THREAD

**Issue by tedsmith** [tedsmith/quickhash#76]
Dear @darealshinji  

So I had a go at using the fine Debian packager you built for us today to get v3.2.0 (confusingly the same numbering of FPC). I got it to run through great, so thanks for the utility. The only snag is the output is quickhash_3.1.0-1_amd64.deb, and not 'quickhash_3.2.0-1_amd64.deb'. Do you know where the script gets the numbering from? I'll then go and update the appropriate file or whatever?

**Comment by darealshinji** [comment]
You need to update `debian/changelog`, the package takes the number from there.

**Comment by tedsmith** [comment]
Ah, got it! Thanks man. Debian package now online. Awesome.
