### ISSUE TITLE
Please add CRC

### ISSUE THREAD

**Issue by i2324561w2** [tedsmith/quickhash#77]
(I wanted to send this from the other site, but somehow I don't see any captcha there)
Can you add CRC/SFV? Sure there are better hashes, but they are slower (in case of many TB you can sure spare some hours..) and in some cases a simple hash is enough; also in the anime scene many use hashes for their files, and they are always CRC.
Thank you.

**Comment by darealshinji** [comment]
I made a request for that a while ago: https://github.com/tedsmith/quickhash/issues/28

**Comment by tedsmith** [comment]
There's been a few people asking about CRC over the last year or so. Has it become popular again for some reason or specific purpose? I don't get it thought - CRC is a rather ancient checksum. And whilst I do often favour old ways and older technology, particularly with cars and such, I'm not sure why CRC seems to be in demand now? Wouldn't xxHash be more suitable? Faster than the SHA's but better (?) than CRC?

**Comment by darealshinji** [comment]
CRC is still occasionally used in anime stuff, I guess it's because it's a rather short checksum (8 bytes in ASCII) which can be included in filenames without too much bloat, for example: `[Anime Land] Dragon Quest - Dai no Daibouken (2020) 11 (WEBRip 1080p HEVC EAC3) [E487AEDE].mkv`
I think it's also used in zip files and such, isn't it?

**Comment by tedsmith** [comment]
Added to v3.3.0, pushed to branch but not merged to master yet. Will be available when v3.3.0 is released for all three platforms.

**Comment by tedsmith** [comment]
PS here is a screenshot of said functionality
![Untitled3](https://user-images.githubusercontent.com/1560598/119270701-e64b2c80-bbf5-11eb-8438-9723fd5008ed.png)
![Untitled4](https://user-images.githubusercontent.com/1560598/119270702-e6e3c300-bbf5-11eb-8feb-f7b33dd39df0.png)
