### ISSUE TITLE
Hashes of files that are different / not present are not shown on bottom of comparison log.

### ISSUE THREAD

**Issue by labejar** [tedsmith/quickhash#78]
As stated in title. Using 3.2.0 in Mac OS 10.15.5

Comparing two folders and program identifies a hash mismatch. According to user manual - "The hashes of the files that are different or not present will be shown at the bottom".

When looking @ log file, hashes that are different or not present are NOT shown at the bottom.

Tested multiple times with different folders. Also tested using two folders of dummy .txt files where all pairs are identical except for one.

Log looks like:

```
Compute hashes from FOLDER1
==============
**** HASHES ****
Compute hashes from FOLDER2
==============
**** HASHES ****
Time started: 2021/01/04 00:13:22
Currently searching for files in FOLDER1
Currently searching for files in FOLDER1
Currently searching for files in FOLDER2
Currently searching for files in FOLDER2
Now hashing files in FOLDER1
Now hashing files in FOLDER1
Now hashing files in FOLDER2
Now hashing files in FOLDER2
Result : MIS-MATCH!
Ended at : 2021/01/04 00:13:22
Time taken : 00:00:00
Files in Folder A : 10
Files in Folder B : 10
File count differs by : 0
Finished analysis
```

**Comment by tedsmith** [comment]
Sorry I only just noticed this report. Apologies for not replying sooner. 

OSX is causing me a lot of problems lately, especially since Big Sur, which I don't have myself. So I'm not sure if this is an OSX specific issue or not, because it doesn't do that in Windows or Linux. I'll try to keep it in mind and look at it ASAP.

**Comment by tedsmith** [comment]
v3.3.0 (not out yet but will be in a few days from https://www.quickhash-gui.org/downloads/) will have various comparison options to help with this and other requirements, as shown, thanks to a major overhaul of the SQL syntax. 
![Untitled9](https://user-images.githubusercontent.com/1560598/119270635-8ce2fd80-bbf5-11eb-8d68-72cac40c22c8.png)
