### ISSUE TITLE
Mac OS - cannot create sqlite database

### ISSUE THREAD

**Issue by kieranjol** [tedsmith/quickhash#79]
I"m using Big Sur and the 3.2.0 binary from your website. When I open the app after copying into Applications, a popup appears that says "Cannot create sqlite database. Probably SQLite is not installed on your system."

This results in the Files section bing greyed out and I can't create checksums of directories.

I'd imagine that sqlite should come bundled, as it does on Windows? I have sqlite installed via home-brew, but I doubt that this would matter.

**Comment by tedsmith** [comment]
A few people have reported problems with new OSX version. 

Can you tell me what the following reports:

"find . -name libsqlite3.dylib”  ??

**Comment by tedsmith** [comment]
Cause identified : "New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)"

Now I just need to work out how to resolve it!

**Comment by kieranjol** [comment]
Sorry for delay, pretty sure you don't need this anymore but:
```
find . -name libsqlite3.dylib 
find: ./Library/Application Support/CallHistoryTransactions: Operation not permitted
find: ./Library/Application Support/CloudDocs/session/db: Operation not permitted
find: ./Library/Application Support/com.apple.sharedfilelist: Operation not permitted
find: ./Library/Application Support/Knowledge: Operation not permitted
find: ./Library/Application Support/com.apple.TCC: Operation not permitted
find: ./Library/Application Support/FileProvider: Operation not permitted
find: ./Library/Application Support/com.apple.avfoundation/Frecents: Operation not permitted
find: ./Library/Application Support/CallHistoryDB: Operation not permitted
find: ./Library/Autosave Information: Operation not permitted
find: ./Library/IdentityServices: Operation not permitted
find: ./Library/Messages: Operation not permitted
find: ./Library/HomeKit: Operation not permitted
find: ./Library/Sharing: Operation not permitted
find: ./Library/Mail: Operation not permitted
find: ./Library/Accounts: Operation not permitted
find: ./Library/Safari: Operation not permitted
find: ./Library/Suggestions: Operation not permitted
find: ./Library/Containers/com.apple.VoiceMemos: Operation not permitted
find: ./Library/Containers/com.apple.archiveutility: Operation not permitted
find: ./Library/Containers/com.apple.Home: Operation not permitted
find: ./Library/Containers/com.apple.Safari: Operation not permitted
find: ./Library/Containers/com.apple.iChat: Operation not permitted
find: ./Library/Containers/com.apple.CloudDocs.MobileDocumentsFileProvider: Operation not permitted
find: ./Library/Containers/com.apple.mail: Operation not permitted
find: ./Library/Containers/com.apple.Notes: Operation not permitted
find: ./Library/Containers/com.apple.news: Operation not permitted
find: ./Library/Containers/com.apple.stocks: Operation not permitted
find: ./Library/PersonalizationPortrait: Operation not permitted
find: ./Library/Metadata/CoreSpotlight: Operation not permitted
find: ./Library/Cookies: Operation not permitted
find: ./Library/Caches/com.apple.HomeKit: Operation not permitted
find: ./Library/Caches/com.apple.HomeKit.configurations: Operation not permitted
find: ./Library/Caches/CloudKit: Operation not permitted
find: ./Library/Caches/com.apple.ap.adprivacyd: Operation not permitted
find: ./.Trash: Operation not permitted
```

**Comment by tedsmith** [comment]
Yes, it turns out that Big Sur they have removed all the SDK libraries!!!!! And developers are instead expected to either ship libraries with their applications, or, use Apples dedicated development platform (XCode) where this is handled. So I need to work out how to ship the library with QH to resolve said issue. Thanks for the reply anyway.

**Comment by tedsmith** [comment]
This will be resolved with v3.3.0 which is in Github as a branch but not yet compiled or released.

**Comment by kieranjol** [comment]
You're truly amazing, thank you!!

K

**Comment by tedsmith** [comment]
I am humbled by your high praise but I only worked it out thanks to the open source community. 

Basically I have had to create three separate compiler directives for the loading of sqlite libraries; one for each operating system, which I kind of had before but now, for OSX, there is no file path lookup, as it loads it from the cache. The downside is it means v3.3.0 won't run on older OS X versions, but that's the nature of the beast. Can't win em all!

**Comment by tedsmith** [comment]
@kieranjol kieranjol - if I get a beta compiled for OSX, do you want to try it out for me?

**Comment by kieranjol** [comment]
Absolutely, I’ll test ASAP!

**Comment by tedsmith** [comment]
@kieranjol that is great news. The only snag, is that in true OSX style, while I was trying out some of the new features that are working fine on Windows, and I was just quickly checking they also worked fine on OSX and Linux, sadly, OSX is causing me more pain by complaining at the UNIQUE setting of an SQL statement, for reasons I entirely cannot understand right now! Urgh. 

Keep an eye on your Inbox. I'll try to get a beta to you ASAP. But I need to go to bed!

**Comment by kieranjol** [comment]
Thank you, looking forward to it and best of luck with the troubleshooting!

**Comment by tedsmith** [comment]
The latest problem as it turns out is that new SQL code has been added that uses v3.50 of sqlite. For windows I've compiled dll to ship. No fuss. But not so easy on Linux or OS X! I've worked it out for Linux. But, as usual, OSX remains the challenge. 

I want to release a beta that is at least functional for all the platforms even if it has some squeaks

**Comment by tedsmith** [comment]
OK, sorry for long wait. Can you download the attached zip, extract the "app" file to a folder in your user space. e.g. Desktop or Documents. Note that for OSX, it wont use any of the libraries in libs so you don't need that, but it may be interesting to know what happens for you if it is not there. And when it is there. Up to you. But hopefully, this will "just work" on Big Sur, now. Though you will likely have to give it permission to execute through your Apple security settings. 
[QuickHash-GUI-v3.3.0.zip](https://github.com/tedsmith/quickhash/files/6493135/QuickHash-GUI-v3.3.0.zip)

**Comment by kieranjol** [comment]
It works! I just ran it from Downloads.
Everytime I ran a hash on a single File, I would get this popup - regardless of file format:
<img width="254" alt="Screenshot 2021-05-17 at 16 56 52" src="https://user-images.githubusercontent.com/1127102/118519505-18a9e500-b731-11eb-9ff3-a4c1f947c782.png">
though that's a separate issue.

Thanks so much for sticking with this!

**Comment by tedsmith** [comment]
Ah ok. I'll fix that next (a new feature I added but it's not supposed to show that for every file) but I'm pleased it works!

**Comment by tedsmith** [comment]
I will try to recompile another copy tonight. I worked in this further last night but it was late and I couldn't be bothered to recompile. When I upload it perhaps you can try again? What time zone are you in?

**Comment by kieranjol** [comment]
Absolutely! I’m in Ireland so it’s GMT here.

**Comment by tedsmith** [comment]
Good man. Please try attached...if you would be so kind. Same drill as before. Many thanks. 
[Quickhash-GUI.zip](https://github.com/tedsmith/quickhash/files/6504902/Quickhash-GUI.zip)

**Comment by kieranjol** [comment]
Hi, sorry for delay. I was in leave but will test this Monday!

K

**Comment by tedsmith** [comment]
There will likely be another beta out for you to try by then. So watch this space for updates...

**Comment by tedsmith** [comment]
And here it is ...
[Uploading Quickhash-GUI-v3.3.0-OSX-Beta2.zip…]()

**Comment by kieranjol** [comment]
Ha amazing, thanks Ted.

**Comment by tedsmith** [comment]
Since uploading that, the "Environment Check" in the About menu is now available for Windows Linux and OSX. And further improvements have been done to the E01 file hashing but that feature is not part of OSX yet so nothing new for you to check there either. But as both are largely minor in your regard, the beta of yesterday will still suffice. In other words no impact on the core of the program. I think in your case you just want to make sure it works - opens, and can compute some hashes.

**Comment by tedsmith** [comment]
PS...I am very close to releasing v3.3.0 now. I just have one or two friends checking some things out. Everything seems to be working fairly well across all three platforms.

**Comment by kieranjol** [comment]
Hi Ted, the beta is working great, no issues, thank you so much for all your hard work!

**Comment by tedsmith** [comment]
Music to my ears. Thanks. I'm planning release of v3.3.0 on Saturday 29th as it will be the 10 year anniversary of QuickHash and at the same time we approach 1 million downloads. So a double celebration made worthy I hope by a big new release that this is. Keep your eye on www.quickhash-gui.org for the official release. And thanks for your initial bug issue that has helped solve this problem. On that note I'll close it.
