### ISSUE TITLE
Packaging also needs build-essential 

### ISSUE THREAD

**Issue by tedsmith** [tedsmith/quickhash#80]
@darealshinji 

Just tried out the new v3.3.0 packager on a new Linux Mint 19.3 install with updates. One extra dependency the packager has is build-essential. I only mention it to add to the README. Most of us have that installed already of course so you may have just not noticed it was needed. Perhaps add to the README? I could do it myself but as its your thing perhaps best for you to if it is definately the case.

**Comment by darealshinji** [comment]
You're right. Mentioned in Readme: https://github.com/tedsmith/quickhash/commit/ff15d4272bc50d4fc900f8a8b04290fed4815d33
