### ISSUE TITLE
Hash Files with HashList

### ISSUE THREAD

**Issue by jdtissot** [tedsmith/quickhash#81]
Hi,
I got hash list files from https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/10.9.0-live+nonfree/amd64/iso-hybrid/. I download SHA512SUMS file. I can easily compare my downloaded files with sha512sum -c SHA512SUMS Linux command.

This SHA512SUMS file contains hashes followed by 2 spaces and files names in Linux delimiter line terminator (LF).

I try to use QuickHash to do the same comparison on Windows. I chose SHA512, set my delimiter to space, load my HashList file and select my folder, but I don't get correct results.

Which is the correct format for the HashList file ? I try with CR-LF terminator, replace spaces by tab with the same result.
[SHA512SUMS.txt](https://github.com/tedsmith/quickhash/files/6564350/SHA512SUMS.txt)
![CaptureQuickHash](https://user-images.githubusercontent.com/8268244/120064601-53831580-c06d-11eb-9283-9059f206afe5.PNG)

**Comment by tedsmith** [comment]
Please refer to page 21 of the user manual. Basically, the hash list has to be a single list of hashes. Nothing else .
