### ISSUE TITLE
Icon missing from taskbar

### ISSUE THREAD

**Issue by darealshinji** [tedsmith/quickhash#83]
When compiled with the Makefile the icon is missing in the taskbar.
You can tell by the filesize that quickhash.res is missing the icon data.
I thought this was fixed.

**Comment by tedsmith** [comment]
Maybe the generation of the new logo has messed it up? I'm pretty sure it showed up when I ran it on my Linux mint system but I might be ck fusing it with the compiler binary edition.

**Comment by darealshinji** [comment]
Figured out the issue. Made a pull request and added a note inside the Linux project file.

**Comment by tedsmith** [comment]
Good man. That is indeed a big simplification. Very tidy work. 

I'll do a merge when I get chance tonight (having a non computer day today) and rebuild the package.
