### ISSUE TITLE
Division by Zero Error

### ISSUE THREAD

**Issue by Spokey42** [tedsmith/quickhash#86]
Not a serious problem but I can get this divide by zero by dragging an empty/zero byte file to the program in the file tab.  Worked fine once I saved the file and re-dragged.

![image](https://user-images.githubusercontent.com/49701103/120909723-e6134e00-c645-11eb-98a7-cf3d8678e304.png)

**Comment by tedsmith** [comment]
That version is about 3 years old. Please try with v3.3.0. Should be OK.

**Comment by Spokey42** [comment]
I upgraded and it still does it.  Doesn't really bother me as it was a mistake on my part.  To test I just did a right click on the desktop (win 10 pro 20H2).  Dragged that to quickhash.






*Bill Page*
PO Box 266
Flagtown, NJ 08821-0266
***@***.**** ***@***.***>
- - -

**Comment by tedsmith** [comment]
OK. If it is still an issue then I need to check it out. Can you explain what you are doing step by step? What action is actually triggering the error please?

**Comment by Spokey42** [comment]
When I first found it, it was by mistake.  I had downloaded something (video lan / vlc) and was checking the download against the hash. 

The mistake was that I created a text file for the hash value.  I opened that up and pasted the hash in but didn't save it so it was still a 0 byte/empty file.  I then mistakenly dragged that empty file (instead of the downloaded program) to QuickHash and got the error.

As you can see, a string of unlikely mistakes on my part but thought you would like to know.  I doubt this will occur very often.

The test I did today on the current version was simple.

 1. I right-clicked on the windows desktop and and clicked New->text file.
 2. Pressed the carriage return to exit the file renaming that you are left in.  So that created an empty / 0 byte file. 
 3. Opened QuickHash
 4. Dragged this file to QuickHash




*Bill Page*
PO Box 266
Flagtown, NJ 08821-0266
***@***.**** ***@***.***>
- - -

**Comment by tedsmith** [comment]
Ah, ok. That makes sense. So you're dragging and dropping a zero byte file I think. 

In that case yes, I need to formulate a better error response but as you allude, a file of zero bytes can't really be hashed. I say "can't"...what I mean is it can be, but you'll always get the same nonsensical initialisation hash (for sha1 it will always start DA39 for example). 

Thanks for the note. I'll add it to the to do for the next version. 

Ted

**Comment by Spokey42** [comment]
/Ah, ok. That makes sense. So you're dragging and dropping a zero byte file I think./

Yes



*Bill Page*
PO Box 266
Flagtown, NJ 08821-0266
***@***.**** ***@***.***>
- - -

**Comment by tedsmith** [comment]
The latest [code commit ](https://github.com/tedsmith/quickhash/blob/v3.3.1/unit2.pas#L4389) for v3.3.1 branch addresses and fixes this issue. When the new version is released, this shouldn't happen anymore. Thanks for the report.
