### ISSUE TITLE
2nd and 3rd Column Headings Reversed in Clipboard

### ISSUE THREAD

**Issue by notredruide** [tedsmith/quickhash#89]
Have only been using the program for a minute but I noticed that after generating checksums for a folder and copying the grid to the clipboard, the column headings "FileName" and "Filepath" were reversed in the pasted text. 

![QuickHash v3 3 0 (2021) - The easy and convenient way to hash data in Linux, OSX and Windows, 64-bit_009](https://user-
images.githubusercontent.com/42048602/143137891-450e21e6-0acc-4e47-bdcf-6a9e5801cba6.jpg)

![Selection_010](https://user-images.githubusercontent.com/42048602/143137892-22218d7b-d930-4712-a15c-66d880e60e9e.jpg)

I'm running Ubuntu 20.04.3 64-bit.

**Comment by notredruide** [comment]
Hmm, I broke the first jpg upload. Here is the Quickhash grid that was pasted as above:

![QuickHash v3 3 0 (2021) - The easy and convenient way to hash data in Linux, OSX and Windows, 64-bit_009](https://user-images.githubusercontent.com/42048602/143138268-c4f7d851-4ef4-43ed-88fd-cbc39bd03599.jpg)

**Comment by tedsmith** [comment]
Ah yes - you're right. I missed that. I'll get that resolved for the next release.

**Comment by tedsmith** [comment]
Should be fixed in v3.3.1. I have just committed v3.3.1 draft code but its not finished yet. In my tests just now this seems to be resolved but I'll not close it until I'm sure. It was a passing thing I fixed amongst several bigger issues so I need double check.

**Comment by tedsmith** [comment]
Fixed in v3.3.1
