### ISSUE TITLE
Feature Request: Save default Algorithm preferences

### ISSUE THREAD

**Issue by Sheridan-Tech** [tedsmith/quickhash#95]
It would be really nice to be able to save the last used or most frequently used algorithm as the default.
I almost always use SHA256 since that is generally what is provided on most sites, so it would be nice not to have to change it every time.
I am willing to contribute to this if need be.

**Comment by tedsmith** [comment]
Is now in v3.3.3 and will be further improved in v3.3.4 coming in the next few days which also includes Apple OSX release again
