### ISSUE TITLE
v3.3.1 not starting on macOS 12.3.1 Monterey (Intel)

### ISSUE THREAD

**Issue by berezovskyi** [tedsmith/quickhash#99]
Hello,

As the title says:

![image](https://user-images.githubusercontent.com/64734/163672967-9018fe08-ab6d-4374-915f-6581a69f7efe.jpeg)

I tried to gather some relevant items from the Console logs:

> Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Users/driib/Downloads/Quickhash-GUI-AppleOSX-v3-2/Quickhash-GUI.app/Contents/, NSFilePath=/Users/driib/Downloads/Quickhash-GUI-AppleOSX-v3-2/Quickhash-GUI.app/Contents/PlugIns, NSUnderlyingError=0x7fc0d5be97d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

> os_unix.c:45530: (2) open(/var/db/DetachedSignatures) - No such file or directory

> bundle record for <private> will be registered launch-disabled.

> LAUNCH: RBSLaunchRequest FAILURE <private> com.company.Quickhash-GUI <private> 0x0-0x86e86e failed with error Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600001aa7ba0 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

> handle LS launch error: {\n    Action = oapp;\n    AppMimimumSystemVersion = "10.8";\n    AppPath = "/Users/driib/Downloads/Quickhash-GUI-AppleOSX-v3-2/Quickhash-GUI.app";\n    ErrorCode = "-10810";\n}

> Connection from process 476 does not have the required entitlement com.apple.private.iscsuia

> rejecting read of { kCFPreferencesAnyApplication, driib, kCFPreferencesAnyHost, /Users/driib/Library/Preferences/.GlobalPreferences.plist, managed: 0 } from process 1342 (contentlinkingd) because accessing these preferences requires user-preference-read or file-read-data sandbox access

> Couldn't read values in CFPrefsPlistSource<0x7fd604a09600> (Domain: kCFPreferencesAnyApplication, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: Yes): accessing these preferences requires user-preference-read or file-read-data sandbox access

I hope these were in any way relevant and thank you for maintaining this open-source app, Ted!

**Comment by kieranjol** [comment]
I can also confirm this issue on macOS

**Comment by zoemax** [comment]
I was having the same issue on macOS 12.3.4 (beta)
**I was able to fix by:**
 unzip the tar file.
 change into the directory,  (ie: cd Downloads/Quickhash-GUI-AppleOSX-v3.3.1/Quickhash-GUI.app/Contents/MacOS )

-rw-------@ 1  xx-xxx   staff  22008768 Jan  6 12:24 Quickhash-GUI

Change permissions. 
-rwxr-xr-x@ 1 xx-xxx  staff  22008768 Jan  6 12:24 Quickhash-GUI

and it ran fine ( after allowing in ( system Prefs / General )
![QuickHash331](https://user-images.githubusercontent.com/70059451/163836069-121ef6c4-a439-4eb5-a51e-c8fb62bfa3d9.jpg)

cheers

**Comment by tedsmith** [comment]
This is asked often. So much so I took the time to write it in a FAQ so there is a FAQ in the FAQ for it https://www.quickhash-gui.org/about-quickhash-gui/faqs/#qaef-1643 

Developing for OSX is a bit of a mystery, and Apple make it harder with every release. As @zoemax says, you have to make the inner binary of the .app executable. I have no idea how to make an App for Catalina or above that does not require this step. It's npot the fault of QuickHash - it is OSX and its perculiar ways. Answers on a postcard. Meanwhile, closed.

**Comment by zoemax** [comment]
FAQ’s ?

 now thats there’s a novel idea!


 Thank you - I think this is the first thing I’ve resolved on my own in the past 12 years since retirement!

cheers!

dan



On Apr 26, 2022, at 14:50, Ted Smith ***@***.***> wrote:


This is asked often. So much so I took the time to write it in a FAQ so there is a FAQ in the FAQ for it https://www.quickhash-gui.org/about-quickhash-gui/faqs/#qaef-1643 <https://www.quickhash-gui.org/about-quickhash-gui/faqs/#qaef-1643>
Developing for OSX is a bit of a mystery, and Apple make it harder with every release. As @zoemax <https://github.com/zoemax> says, you have to make the inner binary of the .app executable. I have no idea how to make an App for Catalina or above that does not require this step. It's npot the fault of QuickHash - it is OSX and its perculiar ways. Answers on a postcard. Meanwhile, closed.
